import { useState } from "react";
import { analyzeBug, setSaved } from "../services/api";
import StatusBadge from "../components/StatusBadge";

const initial = { title: "", description: "", programmingLanguage: "JavaScript", errorMessage: "", expectedBehavior: "", actualBehavior: "", stepsToReproduce: "" };

export default function AnalyzePage() {
  const [form, setForm] = useState(initial); const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setError(""); if (!form.title.trim() || !form.description.trim()) { setError("A bug title and description are required."); return; } setLoading(true); try { const { data } = await analyzeBug(form); setResult(data.analysis); } catch (err) { setError(err.response?.data?.message || "Unable to analyze this report. Check the backend and database connection."); } finally { setLoading(false); } };
  const reset = () => { setForm(initial); setResult(null); setError(""); };
  if (result) return <div><div className="page-heading"><div><p className="eyebrow">ANALYSIS COMPLETE</p><h1>{result.title || form.title}</h1><p className="muted">A structured read on what might be happening and where to look next.</p></div><button className="button button-secondary" onClick={reset}>Analyze another</button></div><div className="result-layout"><section className="result-main"><div className="result-summary"><div className="result-badges"><StatusBadge value={result.severity} /><StatusBadge value={result.priority} /></div><p>{result.summary}</p></div><ResultSection title="Possible cause" text={result.possibleCause} /><ResultSection title="Suggested fix" text={result.suggestedFix} /><ResultSection title="Developer advice" text={result.developerAdvice} /><div className="result-section"><h3>Testing suggestions</h3><ul>{result.testingSuggestions.map((item) => <li key={item}>{item}</li>)}</ul></div></section><aside className="result-side"><div className="detail-card"><span>Category</span><strong>{result.category}</strong></div><div className="detail-card"><span>Language</span><strong>{result.programmingLanguage}</strong></div><div className="detail-card"><span>Report</span><strong>{form.title}</strong></div><button className="button button-secondary full-button" onClick={() => setSaved(result._id, !result.isSaved).then(() => setResult({ ...result, isSaved: !result.isSaved }))}>{result.isSaved ? "Remove from saved" : "Save report"}</button></aside></div></div>;
  return <div><div className="page-heading"><div><p className="eyebrow">NEW ANALYSIS</p><h1>What is going wrong?</h1><p className="muted">Give BugWise enough context to turn a vague symptom into a useful debugging plan.</p></div></div><form className="form-panel" onSubmit={submit}><div className="form-section"><h2>Core report</h2><div className="field-grid"><label>Bug title<input name="title" value={form.title} onChange={update} placeholder="Example: Login button does nothing" /></label><label>Programming language<select name="programmingLanguage" value={form.programmingLanguage} onChange={update}>{["JavaScript", "Java", "Python", "C++", "C#", "PHP", "Other"].map((item) => <option key={item}>{item}</option>)}</select></label></div><label>Bug description<textarea name="description" value={form.description} onChange={update} rows="5" placeholder="What happened? Include the context a developer needs to understand the issue." /></label></div><div className="form-section"><h2>Additional context <span>Optional</span></h2><div className="field-grid"><label>Error message<textarea name="errorMessage" value={form.errorMessage} onChange={update} rows="3" placeholder="Paste the relevant error or log output" /></label><label>Expected behavior<textarea name="expectedBehavior" value={form.expectedBehavior} onChange={update} rows="3" placeholder="What should have happened?" /></label><label>Actual behavior<textarea name="actualBehavior" value={form.actualBehavior} onChange={update} rows="3" placeholder="What happened instead?" /></label><label>Steps to reproduce<textarea name="stepsToReproduce" value={form.stepsToReproduce} onChange={update} rows="3" placeholder="1. Open... 2. Click..." /></label></div></div>{error && <div className="form-error">{error}</div>}<div className="form-actions"><span>Gemini returns a structured analysis and saves it to your history.</span><button className="button button-primary" type="submit" disabled={loading}>{loading ? "Analyzing report..." : "Analyze bug with AI"}</button></div></form></div>;
}
function ResultSection({ title, text }) { return <div className="result-section"><h3>{title}</h3><p>{text}</p></div>; }
