import { useCallback, useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { deleteAnalysis, getAnalysis, listAnalyses } from "../services/api";
import StatusBadge from "../components/StatusBadge";

export default function HistoryPage({ savedOnly = false }) {
  const [items, setItems] = useState([]); const [selected, setSelected] = useState(null); const [search, setSearch] = useState(""); const [params] = useSearchParams(); const [error, setError] = useState("");
  const load = useCallback(() => listAnalyses({ search, ...(savedOnly ? { isSaved: true } : {}) }).then(({ data }) => setItems(savedOnly ? data.analyses.filter((item) => item.isSaved) : data.analyses)).catch((err) => setError(err.response?.data?.message || "Unable to load analyses.")), [savedOnly, search]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { if (params.get("id")) getAnalysis(params.get("id")).then(({ data }) => setSelected(data.analysis)).catch(() => { }); }, [params]);
  const remove = async (id) => { await deleteAnalysis(id); setItems(items.filter((item) => item._id !== id)); if (selected?._id === id) setSelected(null); };
  return <div><div className="page-heading"><div><p className="eyebrow">{savedOnly ? "SAVED REPORTS" : "REPORT LIBRARY"}</p><h1>{savedOnly ? "Reports worth keeping." : "Analysis history."}</h1><p className="muted">Search the record of what BugWise has already helped you understand.</p></div></div><div className="toolbar"><input value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === "Enter" && load()} placeholder="Search by title or summary" /><button className="button button-secondary" onClick={load}>Search</button></div>{error && <div className="notice">{error}</div>}<section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Bug title</th><th>Category</th><th>Severity</th><th>Priority</th><th>Date</th><th>Action</th></tr></thead><tbody>{items.map((item) => <tr key={item._id}><td><strong>{item.title}</strong></td><td>{item.category}</td><td><StatusBadge value={item.severity} /></td><td><StatusBadge value={item.priority} /></td><td>{new Date(item.createdAt).toLocaleDateString()}</td><td><button className="table-action" onClick={() => setSelected(item)}>View</button><button className="table-action danger" onClick={() => remove(item._id)}>Delete</button></td></tr>)}</tbody></table></div>{!items.length && <div className="empty-state"><h3>No matching reports</h3><p>Try a different search or create a new analysis.</p></div>}</section>{selected && <div className="detail-drawer"><button className="drawer-close" onClick={() => setSelected(null)}>Close</button><p className="eyebrow">REPORT DETAIL</p><h2>{selected.title}</h2><div className="result-badges"><StatusBadge value={selected.severity} /><StatusBadge value={selected.priority} /></div><Result text={selected.summary} title="Summary" /><Result text={selected.suggestedFix} title="Suggested fix" /></div>}</div>;
}
function Result({ title, text }) { return <div className="drawer-result"><h3>{title}</h3><p>{text}</p></div>; }
